### ISSUE TITLE
Finding the file

### ISSUE THREAD

**Issue by tyalie** [titangene/vscode-hackmd-dark-theme#1]
How do you use this file? The `markdown.styles` attribute seems to accept only files in the local directory or https links. The latter one isn't possible with Github, as Github servers everything as `text/plain` which is refused in this case by VSCode and I don't want to put the styles file into every local directory I'm working on, but would like to have it as a global file somewhere.

**Comment by tyalie** [comment]
Found a solution: [jsdeliver](jsdeliver.com) is able to serve a correctly typed css response.

The link to the markdown theme css file is: https://cdn.jsdelivr.net/gh/titangene/vscode-hackmd-dark-theme/hackmd-theme-dark.css. Instead of specifying a file in `markdown.styles` one can just write this link. It works perfectly.

**Comment by titangene** [comment]
My environment is Ubuntu, so I put CSS in the directory where VS Code extension is installed, for example:

```json
{
  "markdown.styles": [
    "/usr/share/code/resources/app/extensions/markdown-language-features/media/hackmd-theme-dark.css"
  ],
}
```

So I don't need to put CSS in every local directory. However, thank you for providing how to use CDN.
